---
title: "Plotting gaussian longitudinal"
author: "Elisa Verhofstadt"
date: "2023-05-16"
output: html_document
---

```{r}
library(readr)
gaussian_data_G3 <- read_csv("gaussian_data_G3.csv")

```

```{r}
# plot for gaussian data, plot of growth per compound

# melt dataset

#Gaussian Endpoint Models
na.omit(gaussian_data_G3)
#Convert wide-formatted data into long
library(reshape2)
library(dplyr)
gaussian_long <- melt(gaussian_data_G3, measure.vars=c("T_0","T_1", "T_2", "T_3","T_4","T_5","T_6","T_7","T_8","T_9","T_10","T_11","T_12","T_13","T_14","T_15","T_16","T_17","T_18","T_19","T_20"), idvars=c("Flower_index","Compound","Type","Garden","Subplot"), variable.name="Days",value.name="rose.width")
gaussian_long$Compound<-as.factor(gaussian_long$Compound)
gaussian_long$Type<-as.factor(gaussian_long$Type)
gaussian_long$Garden<-as.factor(gaussian_long$Garden)
gaussian_long$Days<-recode(gaussian_long$Days,"T_0"=0,"T_1"=1, "T_2"=2, "T_3"=3,"T_4"=4,"T_5"=5,"T_6"=6,"T_7"=7,"T_8"=8,"T_9"=9,"T_10"=10,"T_11"=11,"T_12"=12,"T_13"=13,"T_14"=14,"T_15"=15,"T_16"=16,"T_17"=17,"T_18"=18,"T_19"=19,"T_20"=20)


# merging dataframe of names with dataframe of gaussian longitudianl data
names_df <- data.frame(Compound = c(1:15),
                       name = c("Distilled water",
                                "Apathic Acid",
                                "Beerse Brew",
                                "Concentrate of Caducues",
                                "Distillate of Discovery",
                                "Essence of Ephiphaneia",
                                "Four in December",
                                "Granules of Geheref",
                                "Kar-Hamel Mooh",
                                "Lucifer's Liquid",
                                "Noospherol",
                                "Oil of John's son",
                                "Powder of Perlimpinpin",
                                "Spirit of Scienza",
                                "Zest of Zen"))
names_garden <- data.frame(Garden = c(1,2),
                           Garden_name = c("North","South"))
names_type <- data.frame(Type = c(1,2),
                         Type_name = c("Floribuna","Hybrid Tea"))
gaussian_long<- merge(gaussian_long,names_df,by="Compound")
gaussian_long<- merge(gaussian_long,names_garden,by="Garden")
gaussian_long<- merge(gaussian_long,names_type,by="Type")

```

```{r}
# first choice: actual data - lines
library(ggplot2)
# only baseline
baseline_df <- gaussian_long %>% na.omit %>% group_by(name, Days) %>% summarize(rose.width = mean(rose.width)) %>% filter(name == "Distilled water")

gaussian_long %>% na.omit %>% filter(name != "Distilled water") %>% group_by(name, Days) %>% summarize(rose.width = mean(rose.width))%>% ggplot(aes(x=Days, y=rose.width, color = factor(name))) +
  geom_line(linewidth = 0.7, alpha = 0.7) +
  geom_line(data = baseline_df, aes(x = Days, y = rose.width), color = 'black', linewidth = 1.5, linetype = 5) +
  labs(color = "Compound",
       y = 'Width (cm)') +
  theme_minimal()
```

```{r}
# second choice: with smoothed lines (lm)
# only baseline
baseline_df <- gaussian_long %>% na.omit %>% group_by(name, Days, Type_name, Garden_name) %>% summarize(rose.width = mean(rose.width)) %>% filter(name == "Distilled water")

gaussian_long %>% na.omit %>% filter(name != "Distilled water") %>% group_by(name, Days, Type_name, Garden_name) %>% summarize(rose.width = mean(rose.width))%>% ggplot(aes(x=Days, y=rose.width, color = factor(name))) +
  geom_smooth(method='lm', se = FALSE, linewidth = 0.7, alpha = 0.7) +
  geom_smooth(data = baseline_df, aes(x = Days, y = rose.width), color = 'black', method='lm', se = FALSE, linewidth = 1.5, linetype = 5) +
  labs(color = "Compound",
       y = 'Width (cm)') +
  theme_minimal() +
  facet_grid(Garden_name~Type_name)
```

```{r}
# option 3: with smoothed lines (lm) + start at point 0

# look at mean value at day 0 for each compound and subtract this from all days of this compound
to_center <- gaussian_long %>% na.omit %>% filter(name != 'Distilled water') %>% group_by(name, Days) %>% summarize(rose.width = mean(rose.width))
starting <- gaussian_long %>% na.omit %>% filter(name != 'Distilled water', Days == 0) %>% group_by(name) %>% summarize(rose.width = mean(rose.width)) 

# loop through compounds
start = 1
end = 21
for (comp in 1:dim(starting)[1]){
    to_center[start:end,]['rose.width'] <- to_center[start:end,]['rose.width'] - as.numeric(starting[comp,]['rose.width'])
    start = start + 21
    end = end + 21
}

# for water only
to_center_water <- gaussian_long %>% na.omit %>% filter(name == 'Distilled water') %>% group_by(name, Days) %>% summarize(rose.width = mean(rose.width))
starting_water <- gaussian_long %>% na.omit %>% filter(name == 'Distilled water', Days == 0) %>% group_by(name) %>% summarize(rose.width = mean(rose.width)) 

to_center_water['rose.width'] <- to_center_water['rose.width'] - as.numeric(starting_water['rose.width'])

```

```{r}
ggplot(to_center, aes(x=Days, y=rose.width, color = factor(name))) +
  geom_smooth(method='loess', se = FALSE, linewidth = 0.7, alpha = 0.7) +
  labs(color = "Compound",
       y = 'Width (cm)') +
  geom_smooth(data = to_center_water, aes(x = Days, y = rose.width), color = 'black', method='loess', se = FALSE, linewidth = 1.5, linetype = 5) +
  theme_minimal() 

```

